---
transport:
  name: winrm
  username: <%= ENV['vmusername'] %>
  password: <%= ENV['vmpassword'] %>

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
    configuration_script_folder: SharedDscConfig
    configuration_script: examples/Default.ps1
    configuration_data_variable: ConfigurationData

verifier:
  name: pester
  test_folder: SharedDscConfig/Validation

platforms:
  - name: 2012r2_WMF5
    os_type: windows
    shell: powershell
    transport:
      name: winrm

suites:
  - name: SharedDscConfig
    provisioner:
      configuration_script: examples/Default.ps1
  - name: OtherTestSuite
    provisioner:
        configuration_script: OtherTestSuite.ps1