#
# Module manifest for module 'SQLServerDscConfig'
#
# Generated by: Stu
#
# Generated on: 31/03/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SQLBaselineConfig.schema.psm1'

# Version number of this module.
ModuleVersion = '0.0.1.0'

# ID used to uniquely identify this module, generate new one via [GUID]::NewGuid()
GUID = '420a6f71-bf5a-4628-a14e-ec2f13159e32'

# Author of this module
Author = 'Stu (kewalaka@gmail.com)'

# Company or vendor of this module
CompanyName = 'N/A'

# Copyright statement for this module
Copyright = '(c) 2019 Stu. All rights reserved.'

}

